name: Release (Docker)

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm i -g pnpm@10
      - name: Install dependencies
        run: |
          pnpm -v
          pnpm install --frozen-lockfile

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push images for apps
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-api
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-catalog
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-marketdata
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-analysis
          build-args: |
            APP=api
          provenance: false

      - name: Build/push catalog
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-catalog
          build-args: APP=catalog
          provenance: false

      - name: Build/push marketdata
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-marketdata
          build-args: APP=marketdata
          provenance: false

      - name: Build/push analysis
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}-analysis
          build-args: APP=analysis
          provenance: false
